name: Release # Workflow name displayed on GitHub 
on: 
  workflow_dispatch: # Trigger manually 
   branches: main # Branch on which the workflow will run 
jobs: 
   new-release: 
      runs-on: ubuntu-latest 
      steps: 
         - uses: actions/checkout@v3 # Checkout our working repository 
         - name: Conventional Changelog Action
             id: changelog 
             uses: TriPSs/conventional-changelog-action@v3 
             with: 
                 github-token: ${{ secrets.RELEASES } 
                 output-file: "false" 
        - name: Create Release # This action will create the actual release 
             uses: actions/create-release@v1 
             if: ${{ steps.changelog.outputs.skipped == 'false' } 
             env: 
                GITHUB_TOKEN: ${{ secrets.RELEASES } 
                with: tag_name: ${{ steps.changelog.outputs.tag } 
                release_name: ${{ steps.changelog.outputs.tag } 
                body: ${{ steps.changelog.outputs.clean_changelog }